name:                robot-position
version:             0.1.0.0
license:             BSD3

data-files:
- src/exe/compact/track.txt

dependencies:
- base >= 4.7 && < 5
- random

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2

library:
  source-dirs: src/lib

executables:
  robot-position-compact:
    main:                Main.hs
    source-dirs:         src/exe/compact
    dependencies:
    - robot-position

  robot-position-readable:
    main:                Main.hs
    source-dirs:         src/exe/readable
    dependencies:
    - robot-position

  robot-position-fast:
    main:                Main.hs
    source-dirs:         src/exe/fast
    dependencies:
    - robot-position
    - hmatrix
